### ISSUE TITLE
1.1.4 prebuilds for Electron 11 (v85)

### ISSUE THREAD

**Issue by nglgzz** [mongodb-js/kerberos#121]
Hi, 

There are no prebuilds targeting Electron 11 (v85) for the [1.1.4 release](https://github.com/mongodb-js/kerberos/releases/tag/v1.1.4). Is this intended? 

Also seeing that there are other similar closed issues, are these prebuilds uploaded on request, or is there a list somewhere of the supported targets and versions?

**Comment by emadum** [comment]
@nglgzz Thanks for reaching out and sorry about the inconvenience, we were pinned to an old version of node-abi due to a bug in that module, which was causing some newer targets to not build. I've updated to the latest version of node-abi now that the issue has been fixed, and forced a rebuild for the latest release ([1.15](https://github.com/mongodb-js/kerberos/releases/tag/v1.1.5)), and the Electron 11 builds are now there.
