### ISSUE TITLE
Pure JS port of the library?

### ISSUE THREAD

**Issue by davidrapin** [mongodb-js/kerberos#69]
I'm interested in this lib but an perfectly cross-platform version for multi-OS deployment reasons.
My organization is willing to port this library to pure JS if possible. There are some questions that we need to answer first:
- is there any reason this library is binary-based?
- is this library anything more than an implementation of https://tools.ietf.org/html/rfc4121 ?
- are you interested in contributing to a pure-JS port of this library?

**Comment by fubar-coder** [comment]
Isn't RFC4120 required for the communication with the Kerberos Network Authentication Service? Otherwise you'd need to use Win API functions.

**Comment by mbroadst** [comment]
@davidrapin I, for one, would _love_ a pure-js port of this, but haven't looked into what's required and suspect that it is not possible. The reason this is binary-based is most likely because it was the most expedient way to support kerberos in our driver at the time, but as @fubar-coder mentioned there are a number of direct calls to Win API required for proper support here. Should you find a way around that, we would be very interested in collaborating on a solution.

**Comment by davidrapin** [comment]
@mbroadst apparently, a Pure JS will not be possible because or required native bindings. For now options are the following:
- options 1: require java to be installed and offload the kerberos driver to a java application using Java Native API (see http://code.dblock.org/2010/03/26/jna-acquirecredentialshandle-initializesecuritycontext-and-acceptsecuritycontext-establishing-an-authenticated-connection.html or https://stackoverflow.com/questions/5804314/simple-kerberos-client-in-java)
- option 2: use https://www.npmjs.com/package/node-pre-gyp to create and store pre-compiled versions of the binaries for different platforms

**Comment by mbroadst** [comment]
@davidrapin providing pre-compiled binaries is on our roadmap, you can track the progress [here](https://jira.mongodb.org/browse/NODE-1264)
